spring: 
  mvc: 
    view: 
      prefix: /WEB-INF/
      suffix: .jsp
  devtools: 
    restart: 
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:23306/br?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: root
    password: Dpfdlxpzm08!
server:
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
    context-path: /br
  port: 11111